#!/usr/bin/env python3

import logging.config
import yaml

from azsearchconfig import cli

with open('logging.yml', 'r') as f:
    config = yaml.safe_load(f.read())
    logging.config.dictConfig(config)

cli()
